JAVA_HOME=/usr/jdk
CLASSPATH=$JAVA_HOME/lib/
PATH=$PATH:$JAVA_HOME/bin
PUSH_SERVER_LOG_LEVEL=INFO
PUSH_SERVER=/project/push-server/server
export PATH JAVA_HOME CLASSPATH PUSH_SERVER_LOG_LEVEL PUSH_SERVER
